networks:
  kafka-net:
    driver: bridge

volumes:
  clickhouse:

services:
  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - ${PG_PORT}:5432
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    command: ["postgres", "-c", "wal_level=logical", "-c", "timezone=Asia/Ho_Chi_Minh"]
    volumes:
      - ./postgres:/var/lib/postgresql/data
    # 1. This creates an isolated network for our Kafka cluster, ensuring secure communication between containers.
    networks:
      - kafka-net

  kafka1:
    # Image dùng để tạo container
    # Docker sẽ pull image này từ Docker Hub để khởi tạo container
    image: confluentinc/cp-kafka:7.8.0

    # Host name bên trong network của container - dùng khi container khác 
    # trong cùng kafka-net cần trỏ tới container này
    hostname: kafka1

    # Tên container hiển thị khi chạy docker ps, dùng để quản lý container
    # qua Docker CLI 
    container_name: kafka1

    ports:
      - "9093:9093"
      - "9092:9092"
    
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_BROKER_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      # Vote Controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:9093,2@kafka2:9093,3@kafka3:9093'
      # Listener: PLAINTEXT
      KAFKA_LISTENERS: 'PLAINTEXT://kafka1:9092,CONTROLLER://kafka1:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka1:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      CLUSTER_ID: '0gDt4nK2qFB0RwIyKQpS7Kl5rglxiRyEmFwvGZP3ug'
      # 3 replication mỗi topic consumer_offset
      KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR: 3
      # rebalance ngay lập tức
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      # 3 replication mặc định cho mỗi topic thông thường
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      # từ 2 replication xác nhận có bản sao thì mới cho đọc/ghi -> nếu ko thì trả lỗi
      KAFKA_MIN_INSYNC_REPLICAS: 2
    volumes:
      - ./kafka-cluster/kafka1/data:/var/lib/kafka/data
    networks:
      - kafka-net

  kafka2:
    # Image dùng để tạo container
    # Docker sẽ pull image này từ Docker Hub để khởi tạo container
    image: confluentinc/cp-kafka:7.8.0

    # Host name bên trong network của container - dùng khi container khác 
    # trong cùng kafka-net cần trỏ tới container này
    hostname: kafka2

    # Tên container hiển thị khi chạy docker ps, dùng để quản lý container
    # qua Docker CLI 
    container_name: kafka2

    ports:
      - "9095:9093"
      - "9094:9092"
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_BROKER_ID: 2
      KAFKA_PROCESS_ROLES: 'broker,controller'
      # Vote Controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:9093,2@kafka2:9093,3@kafka3:9093'
      # Listener: PLAINTEXT
      KAFKA_LISTENERS: 'PLAINTEXT://kafka2:9092,CONTROLLER://kafka2:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka2:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      CLUSTER_ID: '0gDt4nK2qFB0RwIyKQpS7Kl5rglxiRyEmFwvGZP3ug'
      # 3 replication mỗi topic consumer_offset
      KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR: 3
      # rebalance ngay lập tức
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      # 3 replication mặc định cho mỗi topic thông thường
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      # từ 2 replication xác nhận có bản sao thì mới cho đọc/ghi -> nếu ko thì trả lỗi
      KAFKA_MIN_INSYNC_REPLICAS: 2
    volumes:
      - ./kafka-cluster/kafka2/data:/var/lib/kafka/data
    networks:
      - kafka-net

  kafka3:
      # Image dùng để tạo container
      # Docker sẽ pull image này từ Docker Hub để khởi tạo container
      image: confluentinc/cp-kafka:7.8.0

      # Host name bên trong network của container - dùng khi container khác 
      # trong cùng kafka-net cần trỏ tới container này
      hostname: kafka3

      # Tên container hiển thị khi chạy docker ps, dùng để quản lý container
      # qua Docker CLI 
      container_name: kafka3

      ports:
        - "9097:9093"
        - "9096:9092"
      environment:
        KAFKA_NODE_ID: 3
        KAFKA_BROKER_ID: 3
        KAFKA_PROCESS_ROLES: 'broker,controller'
        # Vote Controller
        KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:9093,2@kafka2:9093,3@kafka3:9093'
        # Listener: PLAINTEXT
        KAFKA_LISTENERS: 'PLAINTEXT://kafka3:9092,CONTROLLER://kafka3:9093'
        KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka3:9092'
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
        KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
        KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
        CLUSTER_ID: '0gDt4nK2qFB0RwIyKQpS7Kl5rglxiRyEmFwvGZP3ug'
        # 3 replication mỗi topic consumer_offset
        KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR: 3
        # rebalance ngay lập tức
        KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
        # 3 replication mặc định cho mỗi topic thông thường
        KAFKA_DEFAULT_REPLICATION_FACTOR: 3
        # từ 2 replication xác nhận có bản sao thì mới cho đọc/ghi -> nếu ko thì trả lỗi
        KAFKA_MIN_INSYNC_REPLICAS: 2
      volumes:
        - ./kafka-cluster/kafka3/data:/var/lib/kafka/data
      networks:
        - kafka-net
  
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-cluster-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092,kafka2:9092,kafka3:9092
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: debezium
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://kconnect:8083
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - kconnect
    networks:
      - kafka-net
  
  kconnect:
    image: debezium/connect:1.9
    container_name: kconnect
    ports:
      - 8083:8083
    environment:
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_statuses
      BOOTSTRAP_SERVERS: kafka1:9092,kafka2:9092,kafka3:9092
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - postgres
    
    networks:
      - kafka-net
  
  simulator:
    build:
      context: .
      dockerfile: Dockerfile
      target: simulator
    container_name: simulator
    ports:
      - "8000:8000"
    environment:
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - PG_DATABASE=${PG_DATABASE}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
    depends_on:
      - postgres
    networks:
      - kafka-net

  spark-master:
    image: apache/spark:latest
    container_name: spark-master
    hostname: spark-master
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master
    networks:
      - kafka-net
    ports:
      - "7070:8080"
      - "7077:7077"
    environment:
      HOME: /tmp
      KAFKA_CONNECTOR_PACKAGE: org.apache.spark:spark-sql-kafka-0-10_2.13:4.2.0
      CLICKHOUSE_HOST: ${CLICKHOUSE_HOST}
      CLICKHOUSE_PORT: ${CLICKHOUSE_PORT}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_TABLE: ${CLICKHOUSE_TABLE}
    volumes:
      - ./spark/app:/app
      - ./spark/data:/data

  spark-worker-1:
    image: apache/spark:latest
    hostname: spark-worker-1
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8091:8091"
    networks:
      - kafka-net
    environment:
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_WORKER_WEBUI_PORT: 8091
      SPARK_PUBLIC_DNS: localhost
    volumes:
      - ./spark/app:/app
      - ./spark/data:/data

  spark-worker-2:
    image: apache/spark:latest
    hostname: spark-worker-2
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8092:8092"
    networks:
      - kafka-net
    environment:
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_WORKER_WEBUI_PORT: 8092
      SPARK_PUBLIC_DNS: localhost
    volumes:
      - ./spark/app:/app
      - ./spark/data:/data

  flink-jobmanager:
    build:
      context: .
      dockerfile: Dockerfile
      target: pyflink
    ports:
      - "8001:8081"
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        gs.create.items.conflict.check.enable: false
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
      - CLICKHOUSE_PORT=${CLICKHOUSE_PORT}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    command: jobmanager
    depends_on:
      - kafka1
      - kafka2
      - kafka3

    networks:
      - kafka-net

  flink-taskmanager:
    build:
      context: .
      dockerfile: Dockerfile
      target: pyflink
    depends_on:
      - flink-jobmanager
    command: taskmanager
    scale: 2
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.numberOfTaskSlots: 4
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
      - CLICKHOUSE_PORT=${CLICKHOUSE_PORT}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    networks:
      - kafka-net


  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    container_name: clickhouse
    ports:
      - "9000:9000"  # Native protocol
      - "8123:8123"  # HTTP protocol
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    volumes:
      - clickhouse:/var/lib/clickhouse
    networks:
      - kafka-net