CREATE TABLE IF NOT EXISTS default.flink__events
(
    id                                      Int64,
    activity_kind                           Nullable(String),
    created_at                              Nullable(DateTime64(3)),
    app_token                               Nullable(String),
    store_id                                Nullable(String),
    app_name                                Nullable(String),
    app_version                             Nullable(String),
    platform                                Nullable(String),
    environment                             Nullable(String),
    sdk_version                             Nullable(String),
    os_name                                 Nullable(String),
    os_version                              Nullable(String),
    device_type                             Nullable(String),
    device_model                            Nullable(String),
    language                                Nullable(String),
    country                                 Nullable(String),
    country_subdivision                     Nullable(String),
    city                                    Nullable(String),
    timezone                                Nullable(String),
    adid                                    Nullable(String),
    gps_adid                                Nullable(String),
    idfa                                    Nullable(String),
    idfv                                    Nullable(String),
    tracker                                 Nullable(String),
    tracker_name                            Nullable(String),
    network_name                            Nullable(String),
    campaign_name                           Nullable(String),
    adgroup_name                            Nullable(String),
    creative_name                           Nullable(String),
    event                                   Nullable(String),
    event_name                              Nullable(String),
    revenue_float                           Nullable(Decimal(18, 6)),
    currency                                Nullable(String),
    reporting_revenue                       Nullable(Decimal(18, 6)),
    reporting_currency                      Nullable(String),
    ad_impressions_count                    Nullable(Decimal(18, 6)),
    ad_mediation_platform                   Nullable(String),
    ad_revenue_network                      Nullable(String),
    ad_revenue_placement                    Nullable(String),
    ad_revenue_unit                         Nullable(String),
    subscription_event_type                 Nullable(String),
    subscription_purchased_at               Nullable(DateTime64(3)),
    subscription_expiration_time            Nullable(DateTime64(3)),
    subscription_cancelled_at               Nullable(DateTime64(3)),
    subscription_transaction_id             Nullable(String),
    subscription_original_transaction_id    Nullable(String),
    subscription_product_id                 Nullable(String),
    subscription_sales_region               Nullable(String),
    reporting_cost                          Nullable(Decimal(18, 6)),
    installed_at                            Nullable(DateTime64(3)),
    click_time                              Nullable(DateTime64(3)),
    impression_time                         Nullable(DateTime64(3)),
    engagement_time                         Nullable(DateTime64(3)),
    impression_based                        Nullable(Bool),
    is_organic                              Nullable(Bool),
    op                                      LowCardinality(String),
    __debezium_ts_ms                        Int64
)
ENGINE = ReplacingMergeTree(__debezium_ts_ms)
ORDER BY (id);

CREATE DATABASE IF NOT EXISTS silver;

CREATE TABLE IF NOT EXISTS silver.events
(
    id                                      Int64,
    activity_kind                           Nullable(String),
    created_at                              Nullable(DateTime64(3)),
    app_token                               Nullable(String),
    store_id                                Nullable(String),
    app_name                                Nullable(String),
    app_version                             Nullable(String),
    platform                                Nullable(String),
    environment                             Nullable(String),
    sdk_version                             Nullable(String),
    os_name                                 Nullable(String),
    os_version                              Nullable(String),
    device_type                             Nullable(String),
    device_model                            Nullable(String),
    language                                Nullable(String),
    country                                 Nullable(String),
    country_subdivision                     Nullable(String),
    city                                    Nullable(String),
    timezone                                Nullable(String),
    adid                                    Nullable(String),
    gps_adid                                Nullable(String),
    idfa                                    Nullable(String),
    idfv                                    Nullable(String),
    tracker                                 Nullable(String),
    tracker_name                            Nullable(String),
    network_name                            Nullable(String),
    campaign_name                           Nullable(String),
    adgroup_name                            Nullable(String),
    creative_name                           Nullable(String),
    event                                   Nullable(String),
    event_name                              Nullable(String),
    revenue_float                           Nullable(Decimal(18, 6)),
    currency                                Nullable(String),
    reporting_revenue                       Nullable(Decimal(18, 6)),
    reporting_currency                      Nullable(String),
    ad_impressions_count                    Nullable(Decimal(18, 6)),
    ad_mediation_platform                   Nullable(String),
    ad_revenue_network                      Nullable(String),
    ad_revenue_placement                    Nullable(String),
    ad_revenue_unit                         Nullable(String),
    subscription_event_type                 Nullable(String),
    subscription_purchased_at               Nullable(DateTime64(3)),
    subscription_expiration_time            Nullable(DateTime64(3)),
    subscription_cancelled_at               Nullable(DateTime64(3)),
    subscription_transaction_id             Nullable(String),
    subscription_original_transaction_id    Nullable(String),
    subscription_product_id                 Nullable(String),
    subscription_sales_region               Nullable(String),
    reporting_cost                          Nullable(Decimal(18, 6)),
    installed_at                            Nullable(DateTime64(3)),
    click_time                              Nullable(DateTime64(3)),
    impression_time                         Nullable(DateTime64(3)),
    engagement_time                         Nullable(DateTime64(3)),
    impression_based                        Nullable(Bool),
    is_organic                              Nullable(Bool),
    op                                      LowCardinality(String),
    __debezium_ts_ms                        Int64
)
ENGINE = ReplacingMergeTree(__debezium_ts_ms)
ORDER BY (id);
