sink_adjust_event_to_bronze:
  app_name: SinkToBronze
  table: adjust_events
  kafka_topic: adjust-dbserver.adjust.event
  kafka_group_id: adjust-event-streaming-consumer
  trigger_interval: "1 minutes"
  shuffle_partitions: 2
