CREATE TABLE IF NOT EXISTS catalog.bronze.adjust_event (
    id INT,
    activity_kind STRING,
    created_at BIGINT,
    app_token STRING,
    store_id STRING,
    app_name STRING,
    app_version STRING,
    platform STRING,
    environment STRING,
    sdk_version STRING,
    os_name STRING,
    os_version STRING,
    device_type STRING,
    device_model STRING,
    language STRING,
    country STRING,
    country_subdivision STRING,
    city STRING,
    timezone STRING,
    adid STRING,
    gps_adid STRING,
    idfa STRING,
    idfv STRING,
    tracker STRING,
    tracker_name STRING,
    network_name STRING,
    campaign_name STRING,
    adgroup_name STRING,
    creative_name STRING,
    event STRING,
    event_name STRING,
    revenue_float DECIMAL(18, 6),
    currency STRING,
    reporting_revenue DECIMAL(18, 6),
    reporting_currency STRING,
    ad_impressions_count DECIMAL(18, 6),
    ad_mediation_platform STRING,
    ad_revenue_network STRING,
    ad_revenue_placement STRING,
    ad_revenue_unit STRING,
    subscription_event_type STRING,
    subscription_purchased_at BIGINT,
    subscription_expiration_time BIGINT,
    subscription_cancelled_at BIGINT,
    subscription_transaction_id STRING,
    subscription_original_transaction_id STRING,
    subscription_product_id STRING,
    subscription_sales_region STRING,
    reporting_cost DECIMAL(18, 6),
    installed_at BIGINT,
    click_time BIGINT,
    impression_time BIGINT,
    engagement_time BIGINT,
    impression_based BOOLEAN,
    is_organic BOOLEAN,
    event_date DATE
)
USING iceberg
PARTITIONED BY (event_date)
