connector.name=iceberg
iceberg.catalog.type=file
iceberg.file-format=PARQUET
hive.metastore.warehouse.dir=s3a://lakehouse/dev/
fs.native-s3.enabled=true
s3.endpoint=http://minio:9000
s3.aws-access-key=${ENV:AWS_ACCESS_KEY_ID}
s3.aws-secret-key=${ENV:AWS_SECRET_ACCESS_KEY}
s3.path-style-access=true
s3.ssl.enabled=false